server:
  port: 8085
spring:
  application:
    name: point-service
  datasource:
    url: jdbc:mariadb://mariadb.database.svc.cluster.local:3306/bodyx_ecommerce?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mariadb123}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
management.endpoints.web.exposure.include: health,info
