apiVersion: apps/v1
kind: Deployment
metadata:
  name: geunuk-frontend
  namespace: healthshop
  labels:
    app: geunuk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geunuk-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: geunuk-frontend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: geunuk-frontend
          image: 192.168.0.13/k8s_project/geunuk-frontend:v1.0-108
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: geunuk-frontend
  namespace: healthshop
spec:
  selector:
    app: geunuk-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: geunuk-frontend-hpa
  namespace: healthshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geunuk-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
