server:
  port: 8084
spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
