server:
  port: 8086
spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://mongodb.database.svc.cluster.local:27017/geunuk_logs
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mongo:
      enabled: true
