server:
  port: 8086
spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://bodyx_writer:writer-pass-1234@mongodb-rs-0.mongodb-rs-headless.database.svc.cluster.local:27017,mongodb-rs-1.mongodb-rs-headless.database.svc.cluster.local:27017,mongodb-rs-2.mongodb-rs-headless.database.svc.cluster.local:27017/geunuk_logs?replicaSet=rs0&authSource=admin
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    mongo:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
